"de_dust2"
{
    "t_arms"                "models/player/custom_player/maoling/neptunia/s-sha/normal/s-sha_arms.mdl"
    "ct_arms"               "models/player/custom_player/maoling/neptunia/neptune/hdd/purpleheart_arms.mdl"
    "t_models"
    {
        "../models/player/custom_player/maoling/neptunia/s-sha/normal/s-sha" ""
    }
    "ct_models"
    {
        "../models/player/custom_player/maoling/neptunia/neptune/hdd/purpleheart" ""
    }
}